### ISSUE TITLE
SCAN rss feed contains no items https://scan-bugs.org:443/portal/webservices/dwc/rss.xml

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/scan#1]
As I was preparing an integration with scan, I noticed that the rss feed is now empty, yesterday many dwca collections were referenced (see attached copy retrieved 2019-09-20)
[rss-20190920.xml.txt](https://github.com/globalbioticinteractions/scan/files/3638986/rss-20190920.xml.txt)

fyi @seltmann @neilcobb 

$ curl "https://scan-bugs.org:443/portal/webservices/dwc/rss.xml"

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"><channel><title></title><link></link><description></description><language>en-us</language></channel></rss>
```

**Comment by neilcobb** [comment]
Accidently removed, Evin needs to fix something, then should be back up within an hour from now

**Comment by jhpoelen** [comment]
@neilcobb thx. 

Btw - as you probably know, there's 126,988 scan records with some associations (e.g., associatedTaxa usage). Nice!

See https://travis-ci.org/globalbioticinteractions/scan/jobs/587910909#L916

**Comment by neilcobb** [comment]
Yep, and I am glad you think that is good, there should be a few more k in other fields like habitat

**Comment by jhpoelen** [comment]
@neilcobb thanks for getting scan rss.xml back up. As far as I can tell,

this archive was removed:

FMNH-FMNHINS DwC-Archive 


and the following collections were added:

MAJC-MAJC DwC-Archive

UD-UDCC DwC-Archive

WIS-IH-WIRC DwC-Archive

**Comment by neilcobb** [comment]
Evin accidently added FMNH, it was removed and below are the collections that have DwC-A files



ANSP-ENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=71>

Academy of Natural Sciences Entomology Collection - LepNet

ANSP-ORTH<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=228>

Academy of Natural Sciences Entomology Collection – OrthopNet

ABS-ARTHARCH<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=104>

Archbold Biological Station Arthropod Collection

ASU-ASUCOB<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=121>

Arizona State University Charles W. O'Brien Collection

ASU-ASUHIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=1>

Arizona State University Hasbrouck Insect Collection

ASU-ASULOB<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=168>

Arizona State University Lois B. O'Brien Collection

BLM-MLFO<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=94>

BLM Mother Lode Field Office: The Bees of Pine Hill Preserve

BYU-BYUC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=18>

Brigham Young University Arthropod Museum

CSU-CSUC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=4>

C.P. Gillette Museum of Arthropod Diversity

CSUEB-CSUEBNHM<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=130>

California State University East Bay Natural History Museum

CU-CUAC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=88>

Clemson University Arthropod Collection

CLEV-CMNHENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=95>

Cleveland Museum of Natural History Invertebrate Zoology Collection

CC-OBE-COCOA<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=183>

Colorado College Arthropod Collection

NAUF-CPMAB<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=3>

Colorado Plateau Museum of Arthropod Biodiversity

DBG-DBGA<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=57>

Denver Botanic Gardens Collection of Arthropods

DMNS-Arac<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=12>

Denver Museum of Nature & Science - Arachnology

DMNS-Ento<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=173>

Denver Museum of Nature & Science - Entomology

DAWIC-DAWIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=214>

Derek A. Woller Insect Collection

DUGWAY-DUG-ENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=53>

Dugway Proving Ground Natural History Collection

UMNH-ENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=15>

Entomology Collection at the Natural History Museum of Utah

PSUC-ENTO<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=126>

Frost Entomological Museum

GPSC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=14>

Gregory P. Setliff Collection - Kutztown University

HDOA-HDOAPPC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=182>

Hawaii Department of Agriculture, Plant Pest Control Branch

UKY-HIC-HIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=44>

Hymenoptera Institute Collection

JMM-JMMI<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=217>

Joseph Moore Museum

KSU-MEPAR<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=80>

K-State Museum of Entomological and Prairie Arthropod Research

KKIC-KKIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=169>

Kojun Kanda Insect Collection

MAJC-MAJC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=96>

M. Andrew Johnston Collection

MISSA-MEM<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=108>

Mississippi Entomological Museum

MNA-WACA<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=176>

Museum of Northern Arizona - Walnut Canyon National Monument Collection

UNM-MSBA<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=5>

Museum of Southwestern Biology, Division of Arthropods

NAUF-NAUF5F<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=177>

NAU Forest Entomology Collection

NMSU-NMSU<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=10>

New Mexico State Collection of Arthropods

UCD-BMEC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=78>

R. M. Bohart Museum of Entomology

SDSU-TAC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=64>

SDSU Terrestrial Arthropods Collection

SSAC-SSAC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=113>

Salvatore S. Anzaldo Collection

SDNHM-SDNHM-ENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=220>

San Diego Natural History Museum Entomology Department

SBMNH-SBMNHENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=99>

Santa Barbara Museum of Natural History Entomology Collection

SDSU-SMIRC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=167>

South Dakota State University, The Severin-McDaniel Insect Research Collection

TTRSNHM (25625)-TTRSLEP (24626)<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=105>

Tall Timbers Research Station Natural History Museum

TAMU-TAMUIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=9>

Texas A&M University Insect Collection

TTU-TTU-Z<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=7>

Texas Tech University - Invertebrate Zoology

MSU-MSUC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=76>

The Albert J. Cook Arthropod Research Collection

BROW-BCIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=172>

The Broward College Insect Collection

DCH-DCEC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=127>

The Davidson College Entomology Collection

UCSC-RMIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=129>

The Kenneth S. Norris Center for Natural History at University of California Santa Cruz

PU-PERC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=58>

The Purdue Entomological Research Collection

UA-UAIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=11>

University of Arizona Insect Collection

UD-UDCC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=69>

University of Delaware Insect Research Collection

GMNH-UGCA<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=56>

University of Georgia Collection of Arthropods

GUAM-ESUG<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=180>

University of Guam Insect Collection

UHIM-UHIM<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=50>

University of Hawaii Insect Museum

MIN-UMSP<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=79>

University of Minnesota Insect Collection

UNR-ENTO<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=81>

University of Nevada, Reno, Museum of Natural History, Entomology Research Collection

UPRM-INVCOL<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=185>

University of Puerto Rico Mayagüez Invertebrate Collection

UTC-UTCI<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=54>

University of Tennessee at Chattanooga

UU-UUIC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=219>

University of Utah Invertebrates Collection

UVM-VTZT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=92>

University of Vermont Zadock Thompson Zoological Collection-Invertebrates

UWYMED-ENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=112>

University of Wyoming Dillon Lab Insect Collection

UDAF-UDAFE<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=17>

Utah Department of Agriculture and Food Entomology Collection

VPI-VTEC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=75>

Virginia Polytechnic Institute and State University Insect Collection

WVW-ENT<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=179>

West Virginia Wesleyan College Katharine B. Gregg Orchid Pollinator Collection

WWU-WWUC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=67>

Western Washington University Insect Collection

WICH-WICHI<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=97>

Wichita State University Collection

UI-WFBM<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=89>

William F. Barr Entomological Museum

WIS-IH-WIRC<https://scan-bugs.org/portal/collections/misc/collprofiles.php?collid=171>

Wisconsin Insect Research Collection

**Comment by seltmann** [comment]
@jhpoelen This goes back to a prior topic. How can we best show people what their data looks like in GloBI? That way each individual collection manager will know how to improve their datasets. 

A few more requirements: 
People will only want to see their own collection data
Need the catalogNumber for the record that has a warning
